 
const CDOclasses = [
    "AlkaliSilicaReaction",
    "AutogenousShrinkageCrack",
    "BendingCrack",
    "Carbonatation",
    "Cavity",
    "ChemicalDamage",
    "ChlorideAttack",
    "CoarseGrainAggregate",
    "ConcreteInhomogeneity",
    "Crack",
    "DiagonalCrack",
    "Efflorescence",
    "HydrationHeatCrack",
    "ImpurityConfinement",
    "LongitudinalCrack",
    "MoistureDamage",
    "MoisturePenetration",
    "PlasticShrinkageCrack",
    "ReinforcementCorrosion",
    "ReinforcementCorrosionCrossSectionReduction",
    "ReinforcementDamage",
    "ReticulatedCrackArea",
    "RustStaining",
    "SettlementCrack",
    "ShrinkageCrack",
    "Sintering",
    "Spalling",
    "SpallingExposedReinforcement",
    "SplittingCrack",
    "StressCorrosionCrack",
    "SulfateAttack",
    "SurfaceCrack",
    "TendonDamage",
    "TendonParallelCrack",
    "TransverseCrack"

];

export default CDOclasses
